// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID        uuid.UUID `db:"id"`
	Detail    string    `db:"detail"`
	IsDone    bool      `db:"is_done"`
	Assignee  string    `db:"assignee"`
	Deadline  time.Time `db:"deadline"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
