// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: tasks.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, detail, assignee, deadline)
VALUES ($1, $2, $3, $4)
RETURNING id, detail, is_done, assignee, deadline, created_at, updated_at
`

type CreateTaskParams struct {
	ID       uuid.UUID `db:"id"`
	Detail   string    `db:"detail"`
	Assignee string    `db:"assignee"`
	Deadline time.Time `db:"deadline"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Detail,
		arg.Assignee,
		arg.Deadline,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Detail,
		&i.IsDone,
		&i.Assignee,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, detail, is_done, assignee, deadline, created_at, updated_at
FROM tasks
order by created_at desc
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Detail,
			&i.IsDone,
			&i.Assignee,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
